addons:
  sauce_connect: true
language: node_js
node_js:
- 0.12
- 4
- 5
- 6
- iojs
script:
- npm test
- node ./ci-tests/runner.js --target saucelabs
notifications:
  email: false
env:
  global:
  - secure: tssdG0VhYE5nk8KGCtI+tuvduHot4R8DkxF+5ips1UPr4UDL2cZisbn59dkaBxgPjWLuc/AWBrqdGnZu0ySS2O17Slp6SsJlGBKr+3BV/IK270QYTcfvWuN3JnBn7Q3C7lnr2WP3dE3uXvVP3USwd0NxMh/GKgYVZN9tr0tNv/24C3xsJF3Ky3An2DfDsXsNcXj6HcnsSM9VVp+TARqU3l9wCEidUKl3nwTaV9nCD+AkbofCHqKojgLVDZaCSGdF6OhVFQ7rMs+ns4t30h1UilRz/ODbpYryMGXIaYBTKTNcgcK0rro0YBepP5d8ES+gy6hcgqLwdu9XuRGtJIaJBru3vxIOWhk3LqZicoJq6nL7aMtHrmaO3v+4iTnmyxDJdSfsaSmnhbjjdI259P/X0Mn0mG29eI56Ap5uEk+0vS06y+VMh8SPYloX7yojt1+m5I+AkpT+LjYM2FrNeXvlHMVW/Mr9+baaEp65lAe/cKq5KcQ8KpM0QgwpjKpxOB708TVJK1dZufLsPkzTa+jgLAfb8vs3hxBLsj0PBpyq+xprpWmqrwF4VDhVGCbd7UVb7wHNfVeNlQobOupTO4zmXRvTMEXiWFWaGa2ITUDwKA/lwY4MNNM8qBoJTXNye/ECk1/garVXJ+bckfeQtJvXH9sWX1K+qSEjdKhwJTugnPY=
  - secure: DsoUk9RGIV1V9MMukqPFrehIJUU27nkF3kiaJlr5iMp7a4O81ciMGBhzZmv4xZagEH7+pm62dvPCm/BBcH8HtHY86C6S1rh0auxt0vlDnVBjeKZ04d3BLHHK4/cjzjViNQs4TdbfwYJ2yXTfkwgLPSb7X7JR/vlB16rfSUGaYR0I6uawLPPld8HMWanuuTk+Xtrx0UI/5YcHAaxhfSs3yPmjwgWBVSUGfk+3Z0JHqtfPsIjIC2VnMvSPj6Ei8C475GDUF/a4Eoa4jnH4/abnCjiER49vf0aM1Ih0w9/Z2SmT5rx/5ntdPhKSwWWOkb6YmKcsKHjIEHzN5uIMM/ld2U5DD9DY1GBaYUq6I5WnE67SgYCGnJeEWravE9XIVG9UHyYNi6S3eRVo62r24QQNHMmIA0xZ9OJ1ixDCOhOLt9EvB3/D+ND3pxlJOQGFY107wfCu0xoEQEDfiFVbbpdKSy1RL7oaP5gKcQjUP9TfW8UD8JALkmIsR94ixKjGuR0KbBgZ0dUpf3tbQ8AjkCNt1f12eKxecSlSeJLV9VHqAtjiuOLDtDNsaaqIUyAhIX9ZvaHWa2XfPFdOFIa1je04bhVb9QJY9iPcVstr/YKIn4/eoC9/A10OtGainmHFJuJhJFiNnOlSI9GdAk96/y/3geFkezwi+9BOYF8t+Setv/E=
