addons:
  sauce_connect: true
language: node_js
node_js:
- 4
- 6
- 7
- 8
- iojs
script:
- yarn test
- node ./ci-tests/runner.js --target saucelabs
notifications:
  email: false
env:
  global:
  - secure: l/r99OCfTAw+DfcEfHyuwDC/y1kICcufk5r8QV/GZErhLvFbcnA6gb4uqdAWhJbGm2KN+yLmi9+GEqI0SjOwsAXRvuabtem8/ZtaHX7kcIYjmS7WLPm5IvQq5utboUDvw+rAkFI33cIHFka6E+N8p4eLh+z369kT7qt3r+s4cMvUGeNvVxhSOTy9srJ+7Sz6uvk96MjwaumOdBwM7RbFXH4GSsBrvsmT2XKdsfRjdh3iOLUeL0mA44xBEGVe9xXjlT535i8gB0nHeElOKiAXlIqVnetUNvC1ARZh4LR/3vvgdHIr7ioHQ+5x+N+CJ7nAPV2WGFTg0hx/+huDsHwlsZU+G3VqMmRjFJw1uC2D+UUjaqhZq1NCDDBmmlWtPDiTW9Mu4vJxmQ7WRh/rYyUGVqkXNbvsYs8k9Zv0fJ2RjTe13urwKn2aVh4WEyLtGRr84rzQtf/Pez4RJ05ho1a6+nlU2tK8mgiUxhC9U+dCh/J6clIadomoKSN/MTtr4yDfCJ5JH4claSeFNVZ2sxytZe3B4r/hJ6pGcF/8KN6sAJ0tvop+uGre8rbZLci1t+PXSTJsnKEP523aZMuRHd7oEI+KybLr98syhwZg+98sh6A+KnZzqlFO2jbTzzEHU9w7nGV35ym/cw2mYbJ8tgZWeEOQ/iwjYkr9abHhEzGH5mc=
  - secure: fu4f3KJG7Yj+N1QzL4vlONsv2PxOEgQ4WtRi07Y/B+OvLnTnbSu1zN+gnS3LJXPaOOG5RV1YUPaQAX7JyP7m1WdJG6H+co9B3AxkHlqL07wN6Hozisaw7DIiCIHD807RA6ztx/wjagTUefqDdjoNJkf7khSZLwwUsxyVAF8+wqO4FVxKiyh4/0q0lKlH3GqNij9VsFFstbhNZYZvWwaPGmfBYJG9YCd70iLDgJJ7rBv/092sfxYicxnDK3E9mvZOiI++YDWnhnZUDADqBU/0F/5WxQFHatC4Iu+SD3yJYNwfIivkTqlrmrx1AJF8wsPiIbnY8JOCggbi4g7Fd5s95URHO9e1QxTqz6lD1MXyfTedYv8SVOzW6PCk6hsWoyqYdv/+2AgnhwoM9J7l0rVG488iZ1zuyfFyYZg4FAmaXBoKMgrJE0dI6UE757BA14hgvDsJ0fLuna4x4Vrvx03iFqr6yoEREVS5XQ2YYynyA3iVft+SQwMb+cUX8LTigWtu/vokk6xgBLS/LWf2sgC5oufJxS/1wrlo/XUjqIaEycE8xVTWQQplqzEupQGX0lTmwi8RSszB/JE/AzXuSI/1XwlxbAc8mSgpJ11KDflfzELODilifXh34EwW5cW9QM2niIbqJM+LKlNjsotXpfbMhYaAgDd0ogOKTTdmtdM30Ss=
